Add AddDefaults
rancher/channelserver pull request #17
Opened 2022-04-01 19:37 UTC by jiaqiluo

Issue: https://github.com/rancher/rancher/issues/36827

# Problem:
We use channelserver to host rke2/k3s version information in rancher/rancher, and we need the ability to set different default versions for different rancher versions.  
This ability should be general enough to support any app and not tied to Rancher. 

# Solution:
This PR adds the support for setting app defaults in the config file. 
An example of the value looks like this 
```
appDefaults:
    - appName: rancher
      defaults:
        - appVersion: '> 2.6.2-0 < 2.6.3-0'
          defaultVersion: '1.20.x'
        - appVersion: '> 2.6.2-0 < 2.6.4-0'
          defaultVersion: '1.21.x'
        - appVersion: '> 2.6.4-0'
          defaultVersion: '1.22.x'
    - appName: anotherApp
      defaults:
        - appVersion: '1.2.x'
          defaultVersion: '1.19.5'
```

# Problem:
In the case where the 404 NotFound is returned from the HTTP GET request, channelserver cannot parse the response's data and is stuck in returning errors. 

# Solution:
This PR adds checks for the response's status code and continues to parse the data only if it is 200.

# Problem:
The default value for the flag `path-prefix` is not applied. 

# Solution:
It is a bug in the urfave/cli module: https://github.com/urfave/cli/issues/1121
This PR bumps github.com/urfave/cli/v2 to v2.4.0 to get the fix 

# Others Improvements:
- update error messages to be clear 
- update the readme and default config file

2022-04-04 15:21 UTC, paynejacob approved these changes

2022-04-04 23:25 UTC, thedadams requested changes
A few minor things.

2022-04-04 23:25 UTC, thedadams commented on pkg/config/get.go
> +		data, _ = data[subKey].(map[string]interface{})
Let's check this potential casting error, just in case.

2022-04-04 23:25 UTC, thedadams commented on pkg/config/get.go
> +	}
This needs to come after the `defer resp.Body.Close()`

2022-04-04 23:25 UTC, thedadams commented on main.go
> +			Usage:       "the app for which the app default versions are for",
```suggestion
			Usage:       "the app for which to retrieve default versions",
```

2022-04-04 23:41 UTC, jiaqiluo commented
@thedadams  Please check[ the latest commit](https://github.com/rancher/channelserver/pull/17/commits/903473d17cefcbe84298dd93ee808f9dcaef77d2) that addresses your comments.

2022-04-05 00:31 UTC, thedadams requested changes

2022-04-05 00:31 UTC, thedadams commented on pkg/config/get.go
> +			return nil, fmt.Errorf("failed to do the type assertion")
```suggestion
			return nil, fmt.Errorf("content at key %s expected to be map[string]interface{}, found %T instead", subKey, data[subKey])
```

2022-04-05 00:31 UTC, thedadams commented on pkg/config/get.go
> +		data, ok := data[subKey].(map[string]interface{})
Avoid variable shadowing so we can make the error message more descriptive.
```suggestion
		subData, ok := data[subKey].(map[string]interface{})
```

2022-04-05 00:31 UTC, thedadams commented on pkg/config/get.go
> +		if err := convert.ToObj(data, &allConfigs); err != nil {
```suggestion
		if err := convert.ToObj(subData, &allConfigs); err != nil {
```

2022-04-05 00:41 UTC, jiaqiluo commented
@thedadams  Please check the latest commit: https://github.com/rancher/channelserver/pull/17/commits/41efe6ca59f80683dd0e006597a478d16de0ee51

2022-04-05 00:43 UTC, thedadams requested changes

2022-04-05 00:43 UTC, thedadams commented on pkg/config/get.go
> +			return nil, fmt.Errorf("content at key %s expected to be map[string]interface{}, found %T instead", subKey, subData[subKey])
```suggestion
			return nil, fmt.Errorf("content at key %s expected to be map[string]interface{}, found %T instead", subKey, data[subKey])
```

2022-04-05 13:26 UTC, thedadams approved these changes

2022-04-05 17:06 UTC, thedadams approved these changes

2022-04-05 17:06 UTC, merged